@apiUrl = http://localhost:8000
@token = {{login.response.body.body.token}}
### VERSION AND CHECK SERVER CONNECTION
GET {{apiUrl}}/version
Content-Type: application/json

### ? Login with the created user
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
    "id": "2345678901",
    "passwd": "123456"
}

### Get Booking List
POST {{apiUrl}}/booking
Content-Type: application/json
Authorization: Bearer {{token}}

{
    
}

### Get Booking List by destination_branch_id
POST {{apiUrl}}/booking/byDestinationBranch
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fields": [],
    "max": 14,
    "current": 0,
    "destination_branch_id": 1
}


#### Add New Booking
POST {{apiUrl}}/booking/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "consignee_name": "John Doe",
    "consignee_mobile": "9876543210",
    "consignor_name": "Jane Smith",
    "consignor_mobile": "9876543211",
    "branch_id": 1,
    "slip_no": 5000,
    "booking_address": "123 Street, City",
    "transport_mode": "Air",
    "paid_type": "Prepaid",
    "cgst": 5.0,
    "sgst": 5.0,
    "igst": 0.0,
    "total_value": 1000.0,
    "package_count": 2,
    "package_weight": 10.5,
    "package_value": 500.0,
    "package_contents": "Electronics",
    "shipper_charges": "ABC Logistics",
    "destination_city_id": 1,
    "destination_branch_id": 1,
    "xp_branch_id": null,
    "created_by": 1,
    "to_pay": "Y",
    "on_account": "1020034",
    "declared_value": 200,
    "other_charges": 200
}


#### Cancle BOOKING
POST {{apiUrl}}/booking/cancel
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "booking_id": 1
}


### AUTO FILL NEW BOOKING
POST {{apiUrl}}/autofill/newBooking
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "search": "1232345435"
}