@apiUrl = http://localhost:8000
@token = {{login.response.body.body.token}}
### VERSION AND CHECK SERVER CONNECTION
GET {{apiUrl}}/version
Content-Type: application/json

### ? Login with the created user
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
    "id": "123456",
    "passwd": "123456"
}


### VERIFY
GET {{apiUrl}}/verify
Content-Type: application/json
Authorization: Bearer {{token}}


#### DELIVERY
POST {{apiUrl}}/delivery
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "max":10,
    "current":0
}


#### DELIVERY
POST {{apiUrl}}/delivery/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "employee_id":10,
    "booking_list":[
        1, 2, 3, 4
    ]
}

#### DELIVERY
POST {{apiUrl}}/delivery/new/booking
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "booking_id":1
}