@apiUrl = http://localhost:8000
@token = {{login.response.body.body.token}}
### VERSION AND CHECK SERVER CONNECTION
GET {{apiUrl}}/version
Content-Type: application/json

### ? Login with the created user
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
    "id": "2345678901",
    "passwd": "123456"
}



### Get all manifests
POST {{apiUrl}}/manifests
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "fields": [],
  "max": 10,
  "current": 0
}


### Get manifest by ID
POST {{apiUrl}}/manifests/byId
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fields" : [],
    "manifests_id": 1
}


### Create a new manifest
POST {{apiUrl}}/manifests/new
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "coloader_id": 0,
  "booking_id": [1],
  "destination_id": 1
}


### Delete a manifest
POST {{apiUrl}}/manifests/delete
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "manifest_id": 1
}


### LIST FOR BOOKINGS
POST {{apiUrl}}/manifests/bookings
Authorization: Bearer {{token}}
Content-Type: application/json

{

}
