### Get Booking List
POST {{apiUrl}}/booking
Content-Type: application/json
Authorization: Bearer {{token}}

{
    
}


#### Add New Booking
POST {{apiUrl}}/booking/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "consignee_id": 1,
  "consignor_id": 1,
  "transport_mode": "Air",
  "paid_type": "Prepaid",
  "destination_city_id": 1,
  "destination_branch_id": 1,
  "address": "23 lan wv",
  "count": 3,
  "weight": 4,
  "value": 1000,
  "contents": "Electronics",
  "charges": 150,
  "shipper": "XYZ Logistics",
  "cgst": 18,
  "sgst": 18,
  "igst": 0
}

