@apiUrl = http://localhost:8000
@token = {{login.response.body.body.token}}
### VERSION AND CHECK SERVER CONNECTION
GET {{apiUrl}}/version
Content-Type: application/json





#### ! GET ALL COMPANIES 
POST {{apiUrl}}/master/companies
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "from": 0
}

#### ! GET COMPANIES BY ID
POST {{apiUrl}}/master/companies/byId
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "company_id": 1
}

#### ! GET ALL COMPANIES BY STATE
POST {{apiUrl}}/master/companies/byState
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "state_id": 1
}

#### ! GET ALL COMPANIES BY STATE
POST {{apiUrl}}/master/companies/byCityId
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "city_id": 1
}

#### ! GET ALL COMPANIES BY STATE
POST {{apiUrl}}/master/companies/byCityId
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "state_id": 1,
    "city_id": 1
}

#### ! ADD NEW COMPANY
POST {{apiUrl}}/master/companies/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Disha Airways",
    "address": "456 Business Park",
    "city_id": 1,
    "state_id": 1,
    "pin_code": "700001",
    "contact_no": "9876543211",
    "email": "info@techcorp.com",
    "gst_no": "29ABCDE1234F1Z5",
    "cin_no": "U12345WB2023PTC123456",
    "udyam_no": "UDYAM-WB-2023-123456",
    "logo": "base64_encoded_string"
}

#### ! DELETE COMPANY
POST {{apiUrl}}/master/companies/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "company_id": "1"
}


### EMPLOYEE LOGIN
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
    "id": "9876542231",
    "passwd": "securePass123"
}

### Fetch Employees
POST {{apiUrl}}/master/employees
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fields" : ["employees.*","users.*"],
    "max" : 10,
    "current" : 0,
    "relation" : "employees.user_id=users.id"
}

### GET ALL USER LIST THAT NOT A EMPLOYE
POST {{apiUrl}}/master/employees/notExist
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "max" : 10,
    "current" : 0,
}

### Fetch Employees ById
POST {{apiUrl}}/master/employees/byId
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "fields": ["employees.","users."],
      "max": 100,
      "current": 0,
      "relation": null,
      "user_id": 1
}



#### FETCH MY EMPLOYEE ID
POST {{apiUrl}}/master/employees/myInfo
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "fields": ["employees.","users."],
      "relation": null,
}

### Fetch Employees by BrachId
POST {{apiUrl}}/master/employees/byBranchId
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "fields" : ["employees.*"],
    "max" : 10,
    "current" : 0,
    "relation" : null,
    "branch_id": 1
}

### Create New Employee
POST {{apiUrl}}/master/employees/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": "2",
  "address": "123 Main St",
  "adhara_no": "123456789012",
  "joining_date": "2025-02-28",
  "branch_id": "1",
  "type": "2"
}

### Delete Employee
POST {{apiUrl}}/master/employees/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "employee_id": 1
}

#### UPDATE Employee
POST {{apiUrl}}/master/employees/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "updates": {
        "employees.address": "ADDRESS"
    },
    "conditions":{
        "employees.id": 1
    }
}


### Get Booking List
POST {{apiUrl}}/booking
Content-Type: application/json
Authorization: Bearer {{token}}

{
    
}


#### Add New Booking
POST {{apiUrl}}/booking/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "consignee_id": 1,
  "consignor_id": 1,
  "transport_mode": "Air",
  "paid_type": "Prepaid",
  "destination_city_id": 1,
  "destination_branch_id": 1,
  "address": "23 lan wv",
  "count": 3,
  "weight": 4,
  "value": 1000,
  "contents": "Electronics",
  "charges": 150,
  "shipper": "XYZ Logistics",
  "cgst": 18,
  "sgst": 18,
  "igst": 0
}



### TRACKING GET
POST {{apiUrl}}/track/bySlipId
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "slip_no": 2
}

### TRACKING GET
POST {{apiUrl}}/track/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "slip_no": 2,
    "status": 2
}

### GET MY ACCESS
POST {{apiUrl}}/master/access
Content-Type: application/json
Authorization: Bearer {{token}}

{

}


### GET ACCESS BY ID
POST {{apiUrl}}/master/access/userId
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 2

}

### GET ACCESS BY ID
POST {{apiUrl}}/master/access/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 2,
    "permission_code": 1111,
    "page_id": 1

}


### GET PAGES BY ID
GET {{apiUrl}}/master/pages
Content-Type: application/json
Authorization: Bearer {{token}}

{

}