services:
    db:
    image: mariadb:latest
    container_name: db-container
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PRODUCTION: ${PRODUCTION}
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/template:/docker-entrypoint-initdb.d



  php:
    build:
      context: .
      dockerfile: docker/build/Dockerfile.build.php
    container_name: php-container
    restart: unless-stopped
    command: "bash start.sh"
    ports:
      - "80:8000"
    volumes:
      - ./backend:/app
      - ./docker/containers/php:/home/vscode
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}