services:
  angular:
    build:
      context: .
      dockerfile: docker/build/Dockerfile.build.angular
    container_name: angular
    restart: unless-stopped
    ports:
      - "4200:4200"
    working_dir: /app
    command: sleep infinity
    volumes:
      - ./mobile:/app
    
  db:
    image: postgres
    container_name: db-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/template:/docker-entrypoint-initdb.d

  php:
    build:
      context: .
      dockerfile: docker/build/Dockerfile.build.php
    container_name: php-container
    restart: unless-stopped
    command: "bash start.sh"
    ports:
      - "80:8000"
    volumes:
      - ./backend:/app
      - ./docker/containers/php:/home/vscode
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}