services:
  react-native:
    build:
      context: ./docker/build
      dockerfile: Dockerfile.react
    container_name: react-native-container
    restart: unless-stopped
    volumes:
      - ./mobile:/app
      - ./docker/containers/react-native:/home/vscode
    ports:
      - "8081:8081"
    working_dir: /app
    command: sleep infinity
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - EXPO_DEVTOOLS_PORT=19002
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
  
  db:
    image: postgres
    container_name: db-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/template:/docker-entrypoint-initdb.d

  php:
    build:
      context: docker/build
      dockerfile: Dockerfile.php
    container_name: php-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./docker/containers/php:/home/vscode
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}