@apiUrl = http://localhost:8000
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.hbVVVjR08wPKctvNOgbGBm8xE_VRDureVLHgOaHj8iI

### VERSION AND CHECK SERVER CONNECTION
GET {{apiUrl}}/version
Content-Type: application/json

### Login with the created user
# @name login
POST {{ apiUrl }}/login
Content-Type: application/json

{
    "id": "1234567890",
    "passwd": "1234"
}

### VERIFY
GET {{apiUrl}}/verify
Content-Type: application/json
Authorization: Bearer {{token}}

#### GET ALL USERS
POST {{apiUrl}}/master/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "from": 0
}

#### ADD NEW USER
POST {{apiUrl}}/master/users/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "mobile": "9876543210",
    "password": "securePass123",
    "first_name": "John",
    "last_name": "Doe",
    "gender": "Male",
    "birth_date": "1990-01-01",
    "address": "123 Main St",
    "email": "john.doe@example.com"
}

#### DELETE USER
POST {{apiUrl}}/master/users/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": "1"
}

#### GET ALL STATES
POST {{apiUrl}}/master/states
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "from":0
}

#### ADD NEW STATE
POST {{apiUrl}}/master/states/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "state_name": "West Bengal"
}

#### DELETE STATE
POST {{apiUrl}}/master/states/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "state_id": "1"
}

#### GET ALL CITIES
POST {{apiUrl}}/master/cities
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "from":0
}

#### ADD NEW CITY
POST {{apiUrl}}/master/cities/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "city_name": "Madnipur",
    "state_id": 1
}

#### DELETE CITY
POST {{apiUrl}}/master/cities/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "city_id": "1"
}

#### GET ALL COMPANIES
POST {{apiUrl}}/master/companies
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "from": 0
}

#### ADD NEW COMPANY
POST {{apiUrl}}/master/companies/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tech Corp",
    "address": "456 Business Park",
    "city_id": 1,
    "state_id": 1,
    "pin_code": "700001",
    "contact_no": "9876543211",
    "email": "info@techcorp.com",
    "gst_no": "29ABCDE1234F1Z5",
    "cin_no": "U12345WB2023PTC123456",
    "udyam_no": "UDYAM-WB-2023-123456",
    "logo": "base64_encoded_string"
}

#### DELETE COMPANY
POST {{apiUrl}}/master/companies/delete
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "company_id": "1"
}